### ISSUE TITLE
Probleme api fetch

### ISSUE THREAD

**Issue by S3kelman** [loic-martinez-freelance/homebridge-rte-tempo#1]
Hello, merci pour ce plugin, depuis le temps que j'en cherchais un!

En revanche on dirait que le fetch de la couleur ne marche pas?
![image](https://github.com/user-attachments/assets/489a29ec-6cb4-40da-810e-005ed9691717)

**Comment by loic-martinez-freelance** [comment]
Bonjour 
Es-ce que l'api a fonctionné depuis ? 
Vue le message elle devait être indisponible, je devrais implémenter un système qui essai plusieurs fois à une intervalle régulière en cas d'échec

**Comment by S3kelman** [comment]
Désolé j'étais abesnt ce weekend, en effet ça marche a priori, génial !
![image](https://github.com/user-attachments/assets/12838ed5-9552-479a-8d6d-344f751bcdf4)

**Comment by loic-martinez-freelance** [comment]
Super, merci pour le retour
